### ISSUE TITLE
Don't know how to build task

### ISSUE THREAD

**Issue by mattiascaricato** [KevinBongart/rake-fast#2]
➜  ~  rake
Generating .rake_tasks...
rake aborted!
Don't know how to build task './bin/--silent'

(See full trace by running task with --trace)

Environment:
OSX Yosemite Version 10.10.1
➜  ~  rake --version
rake, version 10.4.2
➜  ~  rvm --version
rvm 1.26.0 (master) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]
➜  ~  ruby --version
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

If you need some other information, let me know.

**Comment by KevinBongart** [comment]
Hi @mattiascaricato, can you try this: `rake --silent --tasks` please? It looks like on your setup, rake isn't understanding the `--silent` option and tries to run it as a command.

Also, how about `rake --tasks --silent`?

**Comment by mattiascaricato** [comment]
Hi @KevinBongart, thanks for the quick replay.

rake --silent --tasks works fine, also rake --tasks --silent

**Comment by KevinBongart** [comment]
I can't reproduce it over here but it might be a path issue on your side.

Apparently, you're running the `rake` command in your home directory (`~`) and rake is looking for tasks in a `~/bin` directory. Do you have rake tasks in there? I think it'd work better in a dedicated app directory containing a `Rakefile` file For instance, if you had a Rails project in `~/my_rails_app`, you'd try to `cd my_rails_app` and then `rake_refresh`.

Could you also tell me what's inside your `Rakefile` file? (`cat ~/Rakefile`)

**Comment by mattiascaricato** [comment]
I'm not executing rake in my home directory, I just removed the path :P. I didn't know about command "rake_refresh" but I just executed it and the file .rake_tasks was successfully generated.

Thanks!

**Comment by KevinBongart** [comment]
Glad it worked :)

Just in case: [rake-fast also exists as a plugin for oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/rake-fast)

**Comment by milushov** [comment]
same issue and rake_refresh also helped me
