### ISSUE TITLE
Improvements: compatibility with Rails Rakefile & show task descriptions in tab completion

### ISSUE THREAD

**Issue by allenan** [KevinBongart/rake-fast#4]
Hey there,

I tried this out recently and while it's a good solution to slow rake tab completion, I noticed a couple things that could be improved:
1. It's only watching the Rakefile for changes. In Rails, that file almost never changes. Instead, it's loading all the .rake files in the tasks directory. So in addition to watching the Rakefile, it should also look at any .rake files in the current directory and find the greatest modified at time.
2. When completing, it doesn't show the task descriptions like the regular zsh tab completion does. Just the task names.

If this project is still alive, I'd be happy to submit a couple of PRs addressing those issues.

**Comment by KevinBongart** [comment]
Hi @allenan, you're making some good points here. I actually no longer use rake-fast by itself anymore, but via the [oh-my-zsh plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/rake-fast) (which is a direct port of this one).

I think the plugin has more users and more maintainers, so I'd recommend you contribute your PRs directly over there for better feedback.

If you don't use oh-my-zsh, I'm happy to help you get these PRs in here first, and port them there then!

**Comment by allenan** [comment]
Ah, thanks for the heads up! I use oh-my-zsh so I'll check with them over there.
