### ISSUE TITLE
refresh tasks for rails app

### ISSUE THREAD

**Issue by ivanovaleksey** [KevinBongart/rake-fast#5]
Hi, Kevin.
Thank you for great plugin! I like it so mush.

I have found that in Rails app `.rake_tasks` doesn't refresh.
That happens because `Rakefile` always stays the same.
And all `.rake` files is created in `lib/tasks` folder.

I would like to create PR in order to refresh `.rake_tasks` when new tasks are created in `lib/tasks`.
Will your accept it?

Or should I open issue in [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) project?

Thank you.

**Comment by ivanovaleksey** [comment]
Or should I open issue in [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) project?

**Comment by KevinBongart** [comment]
Hi @ivanovaleksey, glad you enjoy this plugin! This sounds like a nice feature. I'd recommend opening a PR directly on the oh-my-zsh where more people will be able to help you get this merged in and more users will benefit from directly. Let me know if you need any help, though!
